spring.application.name=Kaizer-Back

server.port=9090

# Usamos las variables que definiste en el .env
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?user=postgres.rdejygcdktnktackklov&password=WLpsPzdPcGeveezv
spring.datasource.username=postgres
spring.datasource.password=WLpsPzdPcGeveezv
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Seguridad y CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
app.jwt.secret=${JWT_SECRET:bec7a693-e529-4b8e-9d65-ebf25940d39a}
app.jwt.expiration-minutes=${JWT_EXP_MINUTES:1440}

server.address=::


